# Generated by Django 3.2.9 on 2021-11-12 21:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=36, verbose_name='Nombre del tablero'),
        ),
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('PU', 'Publico'), ('PR', 'Privado')], default='PU', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user.png', upload_to=api.models.img_uploader, verbose_name='Foto de perfil'),
        ),
    ]
