# Generated by Django 3.2.9 on 2021-11-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211112_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=36, verbose_name='Nombre'),
        ),
    ]
