# Generated by Django 3.2.9 on 2021-11-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='no_profile.jpg', upload_to='user_images', verbose_name='Foto de perfil'),
        ),
    ]
