# Generated by Django 3.2.9 on 2021-11-18 20:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='no_profile.jpg', upload_to=api.models.img_uploader, verbose_name='Foto de perfil'),
        ),
    ]
