# Generated by Django 3.2.9 on 2021-11-19 20:57

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_replymessage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='replymessage',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
