# Generated by Django 3.2.9 on 2021-11-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_at',
        ),
    ]
