# Generated by Django 3.2.9 on 2021-11-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=36)),
                ('last_name', models.CharField(max_length=36)),
                ('id_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(upload_to='user-images')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('PU', 'Publico'), ('PR', 'Privado')], default='PU', max_length=2),
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('status', models.CharField(choices=[('PU', 'Publico'), ('PR', 'Privado')], default='PU', max_length=2)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.board')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.user')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.user'),
        ),
    ]
